import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ovanos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav>
          <div style={{display: 'flex', flex:'', flexDirection:'row'}}>
            <img src="" alt="" />
            <ul style={{listStyleType:'none'}}>
              <li><Link legacyBehavior href={"/"}><a href="">Home</a></Link></li>
              <li><Link legacyBehavior href={"/menu"}><a href="">Menu</a></Link></li>
              <li><Link legacyBehavior href={"/"}><a href="">Contact</a></Link></li>
            </ul>
          </div>
        </nav>
      </main>
    </>
  )
}
